version: '3'
services:
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=me
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=mydb

    # For persistent db
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data


  testdb:
    # Unfortunately 'extends' is not supported in docker-compose version 3
    image: postgres:latest
    environment:
      - POSTGRES_USER=me
      - POSTGRES_DB=mytestdb


  web:
    build: .
    command: python service.py
    ports:
     - "5000:5000"

    volumes: 
      - .:/myapp
    env_file:
      - .env
    depends_on:
     - db
     - testdb
    restart: unless-stopped
